name = input("Name: "). strip().capitalize()
dob = input("DOB: ").strip()
tel = input("Telephone number: "). strip()
email = input("Email: "). strip()
address = input("Address: ").strip()

userDetails = { "name" : name, "dateOfBirth" : dob, "contactNumber" : tel, "email" : email, "address" : address}
print()
print("Here's your contact card")
print()
print(f"Name: {userDetails['name']}")
print(f"DOB: {userDetails['dateOfBirth']}")
print(f"Tel: {userDetails['contactNumber']}")
print(f"Email: {userDetails['email']}")
print(f"Address: {userDetails['address']}")